---
title: "create extended LN reference for spatial decomposition"
author: ""
date: ""
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

# Load packages

```{r load-packages, warning = FALSE}
suppressPackageStartupMessages({
  library(scater)
  library(dplyr)
  library(reshape2)
  library(Matrix)
  library(purrr)
  library(scran)
  library(Seurat)
  library(tidyverse)
  library(here)
})
```

## color palettes
```{r col palettes}

colBRC <- c("#87c5af", "#94033b", "#fc8f3b", "#2580fe", "#514e72", "#007961",
            "#f4d403", "#38b5fc", "#eb6382", "#8fa38c", "#4673b4", "#b94403",
            "#b7d165", "#9b5662", "#666b73")
names(colBRC) <- c("LZFDC", "MRC", "TBRC","DZFDC","PRC2","RPF", "muralCells", 
                   "PRC1", "BCRC", "medRC","IFRC", "Cxcl9TBRC", "capsular",
                   "LPFRC", "subepithelial")

colLab <- c("#a0b9c4", "#567a83", "#0C3C52",
            "#f3948f", "#cd5f5a", "#b2635e", "#924440", "#74403d", 
            "#af744d", "#ea9a67",
            "#eab562", "#b5a147", "#62714c")


names(colLab) <- c("naiveBcells", "GCBcells","plasmaCells", 
                   "naiveCd4Tcells", "Treg", "Tcm", "Tfh", "proCd4Tcells", 
                   "Cd8Tcells", "NKcells", 
                   "DCs", "Myeloids", "Neutrophils")


colLYM2 <- c("#a0b9c4", "#567a83", "#0C3C52", "#924440", "#eab562", "#b5a147")
names(colLYM2) <- c("naiveBcells", "GCBcells","plasmaCells","Tfh", "DCs",
                   "Myeloids")

colBoth <- c(colBRC, colLab) 
```


## load input data
```{r input data}
basedir <- here()
seuratLY <- readRDS(file = paste0(basedir, 
                              "/data/lympho/allSamples_mergedLab_seurat.rds"))
seuratBRC <- readRDS(file=paste0(basedir, "/data/LN_seurat.rds"))

GCBs <- c("LZBcells", "DZshmBcells", "proDZ")
Myel <- c("mdMacrophages", "trMacrophages", "infMacrophages")
seuratLY$clusterLabel2 <- seuratLY$clusterLabel
seuratLY$clusterLabel2[which(seuratLY$clusterLabel %in% GCBs)] <- "GCBcells"
seuratLY$clusterLabel2[which(seuratLY$clusterLabel %in% Myel)] <- "Myeloids"

seuratLY$label_plus_SLO <- paste0(seuratLY$clusterLabel2, "_", seuratLY$SLO)
seuratLY$clusterLabel <- seuratLY$clusterLabel2


## subset on (naive) LN only
dim(seuratLY)
dim(seuratBRC)
seuratLY <- subset(seuratLY, SLO == "LN")
seuratBRC <- subset(seuratBRC, SLO == "LN" & cond=="naive")
#seuratBRC <- subset(seuratBRC, SLO == "LN")
dim(seuratLY)
dim(seuratBRC)

## plot input data
Idents(seuratLY) <- seuratLY$clusterLabel
DimPlot(seuratLY, reduction = "umap", cols = colLab)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

Idents(seuratBRC) <- seuratBRC$clusterLabel
DimPlot(seuratBRC, reduction = "umap", cols = colBRC)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

# merge BRCs and immune into one reference
```{r merge}

seuratBRC$group <- "BRC"
seuratLY$group <- "LYMPHO"


Idents(seuratLY) <- seuratLY$clusterLabel
Idents(seuratBRC) <- seuratBRC$clusterLabel

## merge
### fix assay and gene names
sceBRC <- as.SingleCellExperiment(seuratBRC)
sceLY <- as.SingleCellExperiment(seuratLY)

genesBRC <- data.frame(geneB=rownames(sceBRC)) %>% 
  mutate(ensID=gsub("\\..*","",geneB))
genesLY <- data.frame(geneL=rownames(sceLY)) %>% 
  mutate(ensID=gsub("\\..*","",geneL))
genesBoth <- full_join(genesBRC, genesLY, by="ensID") %>% 
  mutate(gene=ifelse(is.na(geneL), geneB, geneL)) %>% 
  dplyr::select(ensID, gene)
genesBRC <- genesBRC %>% left_join(., genesBoth, by="ensID")
genesLY <- genesLY %>% left_join(., genesBoth, by="ensID")

rownames(sceBRC) <- genesBRC$gene
rownames(sceLY) <- genesLY$gene

seuratBRC <- as.Seurat(sceBRC)
seuratLY <- as.Seurat(sceLY)

seuratBRC@assays$RNA <- seuratBRC@assays$originalexp
seuratLY@assays$originalexp <- seuratLY@assays$RNA

seuratMerge <- merge(seuratBRC, seuratLY)
seuratMerge <- ScaleData(seuratMerge, assay = "RNA")
seuratMerge <- ScaleData(seuratMerge, assay = "originalexp")

seuratMerge <- runSeurat3::rerunSeurat3(seuratMerge)

## vis merge
(table(seuratMerge$clusterLabel))

Idents(seuratMerge) <- seuratMerge$clusterLabel
DimPlot(seuratMerge, reduction = "umap", cols = colBoth)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

```


## save reference
```{r save reference}

saveRDS(seuratMerge, file = paste0(basedir,
                                  "/data/LN_naiveBRCplusIMMmerged_",
                                  "extendedDatasets_seurat.rds"))
```


## session info
```{r session info}
sessionInfo()
date()
```

