---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Characterize BRC data each SLO indiviually
Characterization LN: [link](CharacterizationLN_CXCL13seurat.html)  
Characterization PP: [link](CharacterizePP_CXCL13seurat.html)  
Characterization Spleen: [link](CharacterizeSpleen_CXCL13seurat.html)  

## Comparative analysis across SLOs
Integrate all CXCL13 pos across SLOs: [link](IntegrateAcrossSLOs.html)  
visualize shared subsets individual SLOs: [link](visFolBRC_individualSLOs.html)  

### SLO specific signatures
Organ specific genes and GO: [link](SLOspecific_signature.html)  
Organ specific signature plots: [link](plotSubsetSLOSignatures.html)  

### Subset specific pattern
Subset specific pathways niche factors: [link](SubsetSpecificGeneSignatures2.html)  
Subset specific pathways signaling PW: [link](SubsetSpecificGeneSignaturesSignaling.html)  
Subset specific signature plots niche factors: [link](plotSubsetSpecificSignatures2.html)  
Subset specific signature plots signaling PW: [link](plotSubsetSpecificSignaturesSignaling.html)  

## Cross SLO mouse Lymphocytes
Merge lymphocyte data: [link](mergeData_lympho.html)  
Characterization lymphocyte data: [link](CharacterizeLympho.html)  

## CellPhoneDB analysis
create CellPhoneDB input: [link](createCPDBinput_immOnly.html)  
visualize CellPhoneDB out: [link](analyseCPDBoutImm.html)  
visualize sel int: [link](CellPhoneDBout_selInt_imm.html)  
Expression of selected niche factor interactions: [link](visSelIntHeatmap.html)  
Expression of selected signaling PW interactions: [link](visSelIntHeatmapSignaling.html)  

